[package]
name = "server"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
rocket-example-api = { path = "../api" }
