[package]
name = "rocket-example-api"
version = "0.1.0"
authors = ["Sam Samai <sam@studio2pi.com.au>"]
edition = "2021"
publish = false

[dependencies]
async-trait = { version = "0.1" }
dto = { path = "../dto" }
entity = { path = "../entity" }
migration = { path = "../migration" }
rocket = { workspace = true }
rocket-okapi-example-service = { path = "../service" }
rocket_cors = "0.6.0"
rocket_okapi = { workspace = true }
serde = "1.0"
serde_json = { version = "1" }
tokio = { workspace = true }

[dependencies.sea-orm-rocket]
path = "../../../sea-orm-rocket/lib" # remove this line in your own project and use the version line
features = [
  "rocket_okapi",
] # enables rocket_okapi so to have open api features enabled
# version = "0.5"
