[package]
name = "rocket-okapi-example-service"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
entity = { path = "../entity" }

[dependencies.sea-orm]
path = "../../../" # remove this line in your own project
version = "1.0.0-rc.7" # sea-orm version
features = [
  "runtime-tokio-native-tls",
  #    "sqlx-postgres",
  #    "sqlx-mysql",
  "sqlx-sqlite",
]

[dev-dependencies]
tokio = { workspace = true }

[features]
mock = ["sea-orm/mock"]

[[test]]
name = "mock"
required-features = ["mock"]
