[package]
name = "entity"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
rocket = { workspace = true }
rocket_okapi = { workspace = true }

[dependencies.sea-orm]
path = "../../../"     # remove this line in your own project
version = "1.0.0-rc.7" # sea-orm version
